spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/uav?useSSL=false
      username: root
      password: root
  http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
  servlet:
      multipart:
        max-file-size: -1
        max-request-size: -1

  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:D:\UAV_img
mybatis:
  mapper-locations:
    - classpath*:/com/lp/sqlMapper/**/*.xml
server:
  port: 8081
custom:
  location: C:/nginx-1.12.2/html
  imgPath: /image/user/
